# Generated by Django 4.2.7 on 2023-12-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_image_link_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='courses',
        ),
        migrations.AddField(
            model_name='booking',
            name='courses',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
