# Generated by Django 4.2.7 on 2023-12-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_userprofile_booked_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
