# Generated by Django 4.2.7 on 2023-12-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_booking_courses_alter_course_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='booked_courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
