# Generated by Django 4.2.7 on 2023-12-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_userprofile_booked_courses_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
