# Generated by Django 4.2.7 on 2023-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_booking_first_name_booking_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
